apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
