image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

mysql:
  database: ecommerce_db
  user: root
  password: root
  rootPassword: root

persistence:
  enabled: true
  size: 5Gi

