---
- hosts: slaves
  become: true
  become_user: root

  tasks:
    - name: Ensure Apache and PHP are at the latest version
      apt:
        name:
          - apache2
          - php
          - php-mysql
        state: latest
        update_cache: true

    - name: Ensure Apache is started and enabled
      systemd:
        name: apache2
        state: started
        enabled: true

    - name: Ensure MariaDB is at the latest version
      apt:
        name: mariadb-server
        state: latest

    - name: Ensure MariaDB is started and enabled
      systemd:
        name: mariadb
        state: started
        enabled: true
